export const POST_DECK_COMMENT_REQUEST = 'POST_DECK_COMMENT_REQUEST';
export const POST_DECK_COMMENT_SUCCESS = 'POST_DECK_COMMENT_SUCCESS';
export const POST_DECK_COMMENT_FAILURE = 'POST_DECK_COMMENT_FAILURE';

export const RESET_POSTING_LIMIT = 'RESET_POSTING_LIMIT';