export const FETCH_ACTIVE_DECK_REQUEST = "FETCH_ACTIVE_DECK_REQUEST";
export const FETCH_ACTIVE_DECK_SUCCESS = "FETCH_ACTIVE_DECK_SUCCESS";
export const FETCH_ACTIVE_DECK_FAILURE = "FETCH_ACTIVE_DECK_FAILURE";

export const RESET_ACTIVE_DECK = 'RESET_ACTIVE_DECK';