export const EDIT_FORM_PROPERTY = 'EDIT_FORM_PROPERTY';
export const UPDATE_SIGN_UP_STATUS = 'UPDATE_SIGN_UP_STATUS';
export const UPDATE_USERNAME_EXIST_STATUS = 'UPDATE_USERNAME_EXIST_STATUS';
export const UPDATE_ACTIVE_USER = 'UPDATE_ACTIVE_USER';
export const TOGGLE_RESET_PASSWORD_VIEW = 'TOGGLE_RESET_PASSWORD_VIEW';