export const FETCH_TOURNAMENTS_REQUEST = "FETCH_TOURNAMENTS_REQUEST";
export const FETCH_TOURNAMENTS_SUCCESS = "FETCH_TOURNAMENTS_SUCCESS";
export const FETCH_TOURNAMENTS_FAILURE = "FETCH_TOURNAMENTS_FAILURE";