export const UPDATE_ACTIVE_DECK_REQUEST = "UPDATE_ACTIVE_DECK_REQUEST";
export const UPDATE_ACTIVE_DECK_SUCCESS = "UPDATE_ACTIVE_DECK_SUCCESS";
export const UPDATE_ACTIVE_DECK_FAILURE = "UPDATE_ACTIVE_DECK_FAILURE";

export const UPDATE_DECK_DESCRIPTION = "UPDATE_DECK_DESCRIPTION";