export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const UPDATE_COMMENT_VOTE = 'UPDATE_COMMENT_VOTE';
export const TOGGLE_COMMENT_BOX = 'TOGGLE_COMMENT_BOX';
export const TOGGLE_PREVIEW = 'TOGGLE_PREVIEW';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_USERS_DETAILS = 'FETCH_USERS_DETAILS';
export const FETCH_USER_VOTED_COMMENTS = 'FETCH_USER_VOTED_COMMENTS';
export const UPDATE_COMMENT_VOTES = 'UPDATE_COMMENT_VOTES';
export const UPDATE_ACTIVE_COMMENT_ID = 'UPDATE_ACTIVE_COMMENT_ID';


export const FETCH_DECK_REQUEST = "FETCH_DECK_REQUEST";
export const FETCH_DECK_SUCCESS = "FETCH_DECK_SUCCESS";
export const FETCH_DECK_FAILURE = "FETCH_DECK_FAILURE";

export const RESET_ACTIVE_DECK = 'RESET_ACTIVE_DECK';