export const FETCH_HOT_DECKS_REQUEST = 'FETCH_HOT_DECKS_REQUEST';
export const FETCH_HOT_DECKS_SUCCESS = 'FETCH_HOT_DECKS_SUCCESS';
export const FETCH_HOT_DECKS_FAILURE = 'FETCH_HOT_DECKS_FAILURE';

export const FILTER_HOT_DECKS = 'FILTER_HOT_DECKS';