export const FETCH_STREAMERS_REQUEST = "FETCH_STREAMERS_REQUEST";
export const FETCH_STREAMERS_SUCCESS = "FETCH_STREAMERS_SUCCESS";
export const FETCH_STREAMERS_FAILURE = "FETCH_STREAMERS_FAILURE";

export const FETCH_STREAMER_REQUEST = "FETCH_STREAMER_REQUEST";
export const FETCH_STREAMER_SUCCESS = "FETCH_STREAMER_SUCCESS";
export const FETCH_STREAMER_FAILURE = "FETCH_STREAMER_FAILURE";

export const RESET_ACTIVE_STREAMER = "RESET_ACTIVE_STREAMER";
