export const FETCH_SHORTENED_USER_DETAILS_REQUEST = 'FETCH_SHORTENED_USER_DETAILS_REQUEST';
export const FETCH_SHORTENED_USER_DETAILS_SUCCESS = 'FETCH_SHORTENED_USER_DETAILS_SUCCESS';
export const FETCH_SHORTENED_USER_DETAILS_FAILURE = 'FETCH_SHORTENED_USER_DETAILS_FAILURE';

export const RESET_SHORTENED_USER_DETAILS = 'RESET_SHORTENED_USER_DETAILS';

