export const FETCH_REDDIT_POST_REQUEST = 'FETCH_REDDIT_POST_REQUEST';
export const FETCH_REDDIT_POST_SUCCESS = 'FETCH_REDDIT_POST_SUCCESS';
export const FETCH_REDDIT_POST_FAILURE = 'FETCH_REDDIT_POST_FAILURE';

export const FETCH_REDDIT_POST_COMMENTS_REQUEST = 'FETCH_REDDIT_POST_COMMENTS_REQUEST';
export const FETCH_REDDIT_POST_COMMENTS_SUCCESS = 'FETCH_REDDIT_POST_COMMENTS_SUCCESS';
export const FETCH_REDDIT_POST_COMMENTS_FAILURE = 'FETCH_REDDIT_POST_COMMENTS_FAILURE';

export const UPDATE_ACTIVE_POST = 'UPDATE_ACTIVE_POST';
export const CLEAR_REDDIT_POST = 'CLEAR_REDDIT_POST';