export const FETCH_ACTIVE_USER_DECKS_REQUEST = 'FETCH_ACTIVE_USER_DECKS_REQUEST';
export const FETCH_ACTIVE_USER_DECKS_SUCCESS = 'FETCH_ACTIVE_USER_DECKS_SUCCESS';
export const FETCH_ACTIVE_USER_DECKS_FAILURE = 'FETCH_ACTIVE_USER_DECKS_FAILURE';