export const DELETE_DECK_COMMENT_REQUEST = 'DELETE_DECK_COMMENT_REQUEST';
export const DELETE_DECK_COMMENT_SUCCESS = 'DELETE_DECK_COMMENT_SUCCESS';
export const DELETE_DECK_COMMENT_FAILURE = 'DELETE_DECK_COMMENT_FAILURE';