export const TOGGLE_DECK_EDIT_VIEW = 'TOGGLE_DECK_EDIT_VIEW';
export const UPDATE_COMMENT_TEXT = 'UPDATE_COMMENT_TEXT';
export const TOGGLE_COMMENT_BOX = 'TOGGLE_COMMENT_BOX';
export const TOGGLE_PREVIEW = 'TOGGLE_PREVIEW';