export const FETCH_REDDIT_POST_COMMENTS_REQUEST = 'FETCH_REDDIT_POST_COMMENTS_REQUEST';
export const FETCH_REDDIT_POST_COMMENTS_SUCCESS = 'FETCH_REDDIT_POST_COMMENTS_SUCCESS';
export const FETCH_REDDIT_POST_COMMENTS_FAILURE = 'FETCH_REDDIT_POST_COMMENTS_FAILURE';

export const CLEAR_POST_COMMENTS = 'CLEAR_POST_COMMENTS';