export const FETCH_DECK_AUTHOR_REQUEST = "FETCH_DECK_AUTHOR_REQUEST";
export const FETCH_DECK_AUTHOR_SUCCESS = "FETCH_DECK_AUTHOR_SUCCESS";
export const FETCH_DECK_AUTHOR_FAILURE = "FETCH_DECK_AUTHOR_FAILURE";

export const RESET_ACTIVE_DECK_AUTHOR = 'RESET_ACTIVE_DECK_AUTHOR';