export const FETCH_HOT_DECKS_REQUEST = 'FETCH_HOT_DECKS_REQUEST';
export const FETCH_HOT_DECKS_SUCCESS = 'FETCH_HOT_DECKS_SUCCESS';
export const FETCH_HOT_DECKS_FAILURE = 'FETCH_HOT_DECKS_FAILURE';

export const FETCH_DECKS_REQUEST = 'FETCH_DECKS_REQUEST';
export const FETCH_DECKS_SUCCESS = 'FETCH_DECKS_SUCCESS';
export const FETCH_DECKS_FAILURE = 'FETCH_DECKS_FAILURE';