export const FIREBASE_SIGN_IN_REQUEST = 'FIREBASE_SIGN_IN_REQUEST';
export const FIREBASE_SIGN_IN_SUCCESS = 'FIREBASE_SIGN_IN_SUCCESS';
export const FIREBASE_SIGN_IN_ERROR = 'FIREBASE_SIGN_IN_ERROR';

export const FIREBASE_SIGN_OUT_REQUEST = 'FIREBASE_SIGN_OUT_REQUEST';
export const FIREBASE_SIGN_OUT_SUCCESS = 'FIREBASE_SIGN_OUT_SUCCESS';
export const FIREBASE_SIGN_OUT_ERROR = 'FIREBASE_SIGN_OUT_ERROR';

export const FIREBASE_REAUTHENTICATE_REQUEST = 'FIREBASE_REAUTHENTICATE_REQUEST';
export const FIREBASE_REAUTHENTICATE_SUCCESS = 'FIREBASE_REAUTHENTICATE_SUCCESS';
export const FIREBASE_REAUTHENTICATE_ERROR = 'FIREBASE_REAUTHENTICATE_ERROR';

export const FIREBASE_RESET_PASSWORD_REQUEST = 'FIREBASE_RESET_PASSWORD_REQUEST';
export const FIREBASE_RESET_PASSWORD_SUCCESS = 'FIREBASE_RESET_PASSWORD_SUCCESS';
export const FIREBASE_RESET_PASSWORD_ERROR= 'FIREBASE_RESET_PASSWORD_ERROR';