export const FIREBASE_SIGN_IN_REQUEST = 'FIREBASE_SIGN_IN_REQUEST';
export const FIREBASE_SIGN_IN_SUCCESS = 'FIREBASE_SIGN_IN_SUCCESS';
export const FIREBASE_SIGN_IN_ERROR = 'FIREBASE_SIGN_IN_ERROR';
export const FIREBASE_SIGN_OUT = 'FIREBASE_SIGN_OUT';
export const FIREBASE_REAUTHENTICATE = 'FIREBASE_REAUTHENTICATE';
export const FIREBASE_RESET_PASSWORD = 'FIREBASE_RESET_PASSWORD';