export const FETCH_REDDIT_POSTS_REQUEST = 'FETCH_REDDIT_POSTS_REQUEST';
export const FETCH_REDDIT_POSTS_SUCCESS = 'FETCH_REDDIT_POSTS_SUCCESS';
export const FETCH_REDDIT_POSTS_FAILURE = 'FETCH_REDDIT_POSTS_FAILURE';

export const UPDATE_FILTERED_POSTS = 'UPDATE_FILTERED_POSTS';
export const UPDATE_ACTIVE_POST = 'UPDATE_ACTIVE_POST';
export const UPDATE_POST_COMMENTS = 'UPDATE_POST_COMMENTS';
export const TOGGLE_COLLAPSE = 'TOGGLE_COLLAPSE';
export const TOGGLE_DOMAIN_FILTER = 'TOGGLE_DOMAIN_FILTER';
export const TOGGLE_CATEGORY_FILTER = 'TOGGLE_CATEGORY_FILTER';