export const FETCH_REDDIT_POSTS_REQUEST = 'FETCH_REDDIT_POSTS_REQUEST';
export const FETCH_REDDIT_POSTS_SUCCESS = 'FETCH_REDDIT_POSTS_SUCCESS';
export const FETCH_REDDIT_POSTS_FAILURE = 'FETCH_REDDIT_POSTS_FAILURE';

export const UPDATE_FILTERED_POSTS = 'UPDATE_FILTERED_POSTS';
export const SELECT_REDDIT_DOMAIN = 'SELECT_REDDIT_DOMAIN';
export const SELECT_REDDIT_CATEGORY = 'SELECT_REDDIT_CATEGORY';

export const RESET_REDDIT_STATE = 'RESET_REDDIT_STATE';