export const FETCH_ACTIVE_DECK_COMMENTS_REQUEST = 'FETCH_ACTIVE_DECK_COMMENTS_REQUEST';
export const FETCH_ACTIVE_DECK_COMMENTS_SUCCESS = 'FETCH_ACTIVE_DECK_COMMENTS_SUCCESS';
export const FETCH_ACTIVE_DECK_COMMENTS_FAILURE = 'FETCH_ACTIVE_DECK_COMMENTS_FAILURE';

export const RESET_ACTIVE_DECK_COMMENTS = 'RESET_ACTIVE_DECK_COMMENTS';